info:
  description: Eureka Client
  url: https://localhost:8762/info

#启动端口
server:
  port: 8762

#Eureka服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#应用名称
spring:
  application:
    name: test-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0