info:
  description: Zuul
  url: https://localhost:8766/info

server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: test-service-zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: test-service-ribbon
    api-b:
      path: /api-b/**
      serviceId: test-service-feign
