info:
  description: Eureka Server
  url: https://localhost:8761/info

server:
  port: 8761

#Eureka服务配置
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/