info:
  description: Config Server
  url: https://localhost:8888/info

server:
  port: 8888

#Eureka服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: test-config-server
  #指定配置文件位置，从git获取
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo

#消息总线配置
rabbitmq:
  host: localhost
  port: 5672
  username: test
  password: test

#取消管理安全认证
management:
  security:
    enabled: false
